-- Server-Driven UI: таблица композиции экранов (issue #284).
--
-- Одна строка на (category, screen) хранит ШАБЛОН композиции экрана в JSONB:
-- упорядоченный список блоков с их `type` и статичными пропсами (БЕЗ живых
-- данных — данные гидрируются на лету из существующих сервисов при запросе).
-- Состав/порядок блоков управляется этой таблицей, а не хардкодом в коде.
--
-- min_catalog_version — минимальная версия каталога блоков, начиная с которой
-- экран (его блоки) можно отдавать клиенту. Сервер исключает из ответа блоки,
-- чей min_catalog_version выше присланного клиентом X-UI-Catalog-Version.
--
-- Сидинг строк — отдельной forward-миграцией (V52), не в этом DDL.

CREATE TABLE ui_views (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category            VARCHAR(64)  NOT NULL DEFAULT 'screen',
    screen              VARCHAR(128) NOT NULL,
    layout_json         JSONB        NOT NULL,
    min_catalog_version INTEGER      NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_ui_views_category_screen UNIQUE (category, screen)
);

COMMENT ON TABLE  ui_views                     IS 'SDUI: шаблон композиции экранов (issue #284). layout_json — список блоков без живых данных.';
COMMENT ON COLUMN ui_views.category            IS 'Категория представления (по умолчанию screen).';
COMMENT ON COLUMN ui_views.screen              IS 'Идентификатор экрана (например, home).';
COMMENT ON COLUMN ui_views.layout_json         IS 'JSONB-шаблон композиции: { screenId, version, blocks: [ { type, ...статичные пропсы } ] }.';
COMMENT ON COLUMN ui_views.min_catalog_version IS 'Минимальная версия каталога блоков, с которой экран/блок отдаётся клиенту.';
